#!/bin/bash

DIR=/sys/class/leds/
DEV=dream_cheeky

MAX=63
OFF="0 0 0"

RED="60 0 0"
GREEN="0 60 0"
BLUE="0 0 60"

LED_R=$(find $DIR -name $DEV??red)/brightness
LED_G=$(find $DIR -name $DEV??green)/brightness
LED_B=$(find $DIR -name $DEV??blue)/brightness

function glow {
    echo $(( $1 < $MAX ? $1 : $MAX )) > $LED_R
    echo $(( $2 < $MAX ? $2 : $MAX )) > $LED_G
    echo $(( $3 < $MAX ? $3 : $MAX )) > $LED_B
    sleep ${4:-1}
}

if [[ -e $LED_R ]] && [[ -e $LED_G ]] && [[ -e $LED_B ]]
then
    echo device found $DIR$DEV
    echo
    echo $LED_R
    echo $LED_G
    echo $LED_B
    echo
    echo -n test
    echo -n .
    glow $RED
    echo -n .
    glow $GREEN
    echo -n .
    glow $BLUE
    glow $OFF 0
    echo done
else
    echo device $DIR$DEV not found. >&2
    exit 1
fi
