#!/bin/bash

DIR=/sys/class/leds/
DEV=dream_cheeky

MAX=63
OFF="0 0 0"

RED="60 0 0"
GREEN="0 60 0"
BLUE="0 0 60"

CYAN="0 60 60"
YELLOW="60 60 0"
MAGENTA="60 0 60"
WHITE="60 60 60"

AQUA="0 30 60"
LIME="30 60 0"
MAUVE="30 0 60"
ORANGE="60 30 0"
PURPLE="60 0 30"
TEAL="0 60 30"

MELLOW="30 20 0"

LED_R=$(find $DIR -name $DEV??red)/brightness
LED_G=$(find $DIR -name $DEV??green)/brightness
LED_B=$(find $DIR -name $DEV??blue)/brightness

function dim {
    glow $(($1/2)) $(($2/2)) $(($3/2)) ${4:-1}
}

function glow {
    echo $(( $1 < $MAX ? $1 : $MAX )) > $LED_R
    echo $(( $2 < $MAX ? $2 : $MAX )) > $LED_G
    echo $(( $3 < $MAX ? $3 : $MAX )) > $LED_B
    sleep ${4:-1}
}

function pulse {
    for i in 64 32 16 8 4 2 1 2 4 8 16 32 64
    do
        glow $(($1/$i)) $(($2/$i)) $(($3/$i)) ${4:-0.1}
    done
}

if [[ -e $LED_R ]] && [[ -e $LED_G ]] && [[ -e $LED_B ]]
then
    echo 💡 device found $DIR$DEV
    [[ $silent ]] || echo -n 🚥 running test .
    glow $RED
    [[ $silent ]] || echo -n .
    glow $GREEN
    [[ $silent ]] || echo -n .
    glow $BLUE
    [[ $silent ]] || echo . done
    glow $OFF 0
else
    echo device $DIR$DEV not found. >&2
    exit 1
fi
